## Example 1 (remove unwanted object) (~10 min)

In [ ]:
import cv2# as apple_pie

In [ ]:
flags_telea = cv2.INPAINT_TELEA
flags_ns = cv2.INPAINT_NS

In [ ]:
# try both 1a and 1b
image = cv2.imread(r'C:\Users\TON93824\Mott MacDonald\Automation & Computational Design - Python\AUS\2021\Session 2 - Computer Vision\Example 1b.jpg')
mask = cv2.imread(r'C:\Users\TON93824\Mott MacDonald\Automation & Computational Design - Python\AUS\2021\Session 2 - Computer Vision\Example 1b - Copy.jpg')
mask = cv2.cvtColor(mask, cv2.COLOR_BGR2GRAY)

output = cv2.inpaint(image, mask, 10, flags=flags_telea)

cv2.imshow('Image', image)
cv2.imshow('Mask', mask)
cv2.imshow('Output', output)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# teaching points
# how it relates to daily work
# pip install --user --trusted-host files.pythonhosted.org --trusted-host pypi.org xxxx
# simplicity of code and power of libraries
# coding structure: import, define, process
# explain each line doing what
# explain what's use of .
# shift tab to read doc
# how to change variables in code
# tab to open available functions
# good practice of define variables ahead
# comment out whole line or # partially
# markdown
# how to make code more readable like writing comprehension
# order of running code / lines
# global and local variables
# import as
# shortcut keys to run all, run above, run below, terminate
# inspect array of image to relate what was learnt in theory

## Example 2 (compare images) (~20 min)

In [6]:
from pdf2image import convert_from_path
import numpy as np
import cv2
import imutils
from skimage.metrics import structural_similarity

In [69]:
# download poppler https://github.com/oschwartz10612/poppler-windows/releases/
# unzip
img1 = convert_from_path(r'C:\Users\TON93824\Mott MacDonald\Automation & Computational Design - Python\AUS\2021\Session 2 - Computer Vision\Example 2.pdf',
                        poppler_path = r'C:\Users\TON93824\Mott MacDonald\Automation & Computational Design - Python\AUS\2021\Session 2 - Computer Vision\poppler-21.03.0\Library\bin')
img1 = np.asarray(img1[0])

img2 = convert_from_path(r'C:\Users\TON93824\Mott MacDonald\Automation & Computational Design - Python\AUS\2021\Session 2 - Computer Vision\Example 2 - Copy.pdf',
                        poppler_path = r'C:\Users\TON93824\Mott MacDonald\Automation & Computational Design - Python\AUS\2021\Session 2 - Computer Vision\poppler-21.03.0\Library\bin')
img2 = np.asarray(img2[0])

In [70]:
min_dimension = 1 #25

img1 = cv2.resize(img1, (0,0), fx=0.5, fy=0.5)
img2 = cv2.resize(img2, (0,0), fx=0.5, fy=0.5)

img1_bw = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
img2_bw = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

score, diff = structural_similarity(img1_bw, img2_bw, full=True)
diff = (diff * 255).astype("uint8")
thresh = cv2.threshold(diff, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)

for cnt in cnts:
    x, y, w, h = cv2.boundingRect(cnt)
    if w > min_dimension and h > min_dimension:
        cv2.rectangle(img1, (x,y), (x+w,y+h), (0,0,255), 2)
#         cv2.circle(img1, (x,y), 10, (0,0,255), 2)

cv2.imshow('img1',img1)
cv2.imshow('img2',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# teaching points
# explain each line doing what
# try convert BGR to RGB
# change colour of rectangular box
# change file path
# read .circle and see what can be changed
# compare rectangle and circle
# change min dimension for better results

## Example 3 (incomplete panorama) (~30 min)

In [50]:
import cv2
import numpy as np
from imutils import paths

In [54]:
input_path = str(r'C:\Users\TON93824\Mott MacDonald\Automation & Computational Design - Python\AUS\2021\Session 2 - Computer Vision\photo set 2')
output_path = str(r'C:\Users\TON93824\Mott MacDonald\Automation & Computational Design - Python\AUS\2021\Session 2 - Computer Vision\photo set 2')

In [55]:
imagePaths = sorted(list(paths.list_images(input_path)))
images = []
for i in imagePaths:
    image = cv2.imread(i)
    image = cv2.resize(image, (0,0), fx=0.25, fy=0.25) # use this line if cv::OutOfMemoryError
    images.append(image)

In [56]:
cv2.imshow('image',cv2.Stitcher_create().stitch(images)[1])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [57]:
cv2.imwrite(output_path + str('\\') + str('done.jpg'), cv2.Stitcher_create().stitch(images)[1])

True

In [ ]:
# teaching points
# how to use list and append
# for loop
# try inspect some images from the list appended
# learn list length
# learn resize
# simple one line can stitch, learn read library doc
# learn write image
# learn about file path, string, int, float
# learn if statement
# multiple output from one line
# time library, %%time
# appreciate the wealth of library and research papers behind

## Spare materials

In [ ]:
# copied from pyimagesearch example
# instead of using photoshop, can also use python to achieve much better result
# https://www.pyimagesearch.com/2020/05/18/image-inpainting-with-opencv-and-python/
# replace with example image and demonstrate
# illustrate same flow, import, define, process
# change one line can feed from webcam

In [73]:
import numpy as np
hsv_buffer_H = 100 # 10
hsv_buffer_S = 30 # 10
hsv_buffer_V = 70 # 40
kernel = np.ones((2,2), np.uint8)

# Inspect background array to identify max / min for webcam input
image_hsv = None   # global
pixel = (20,60,80) # initial seed
cap = cv2.VideoCapture(0)

# mouse callback function
def pick_color(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDOWN:
        pixel = image_hsv[y,x]

        upper =  np.array([pixel[0] + hsv_buffer_H, pixel[1] + hsv_buffer_S, pixel[2] + hsv_buffer_V])
        lower =  np.array([pixel[0] - hsv_buffer_H, pixel[1] - hsv_buffer_S, pixel[2] - hsv_buffer_V])
        print(pixel, lower.tolist(), upper.tolist())

        image_mask = cv2.inRange(image_hsv,lower,upper)
        cv2.imshow("mask",image_mask)

import sys
# global image_hsv, pixel # so we can use it in mouse callback

while True:
    _, frame = cap.read()
#     frame = image # in case want certain pic instead of webcam
    cv2.imshow("frame",frame)

    ## NEW ##
    cv2.namedWindow('hsv')
    cv2.setMouseCallback('hsv', pick_color)

    # now click into the hsv img , and look at values:
    image_hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    cv2.imshow("hsv",image_hsv)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

[  0   0 160] [-100, -30, 90] [100, 30, 230]
[19 49 42] [-81, 19, -28] [119, 79, 112]
[170   5 142] [70, -25, 72] [270, 35, 212]
[173   7 145] [73, -23, 75] [273, 37, 215]
[100 161  84] [0, 131, 14] [200, 191, 154]
[ 98 154  88] [-2, 124, 18] [198, 184, 158]
[105 197  53] [5, 167, -17] [205, 227, 123]
[  0   0 171] [-100, -30, 101] [100, 30, 241]
[ 75   3 183] [-25, -27, 113] [175, 33, 253]


In [ ]:
# green curtain example
# change HSV boundaries manually

In [ ]:
background_img = cv2.imread(r'Z:\python\070. inpaint\opera house.jpg')
kernel = np.ones((2,2), np.uint8)
cap = cv2.VideoCapture(0)

while True:
    _, frame = cap.read()
    
    lower_bound = np.array([-80, -17, 49] ) # manual input
    upper_bound = np.array([120, 43, 189]) # manual input

    mask = cv2.inRange(cv2.cvtColor(frame, cv2.COLOR_BGR2HSV), lower_bound, upper_bound)
    
    background_img = cv2.resize(background_img, (frame.shape[1],frame.shape[0]))
    roi = background_img[0:frame.shape[0], 0:frame.shape[1]]
    cleaned_background_img = cv2.bitwise_and(roi, roi, mask = mask) # change to image_mask_dilate / erode as required
    
    cleaned_foreground_img = cv2.bitwise_and(frame, frame, mask = cv2.bitwise_not(mask)) # reverse of masked image # change to image_mask_dilate / erode as required
    combined_img = cv2.add(cleaned_background_img, cleaned_foreground_img)

    cv2.imshow("combined_img",combined_img)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()